apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: ratathune-server
spec:
  type: ClusterIP
  selector:
    app: ratathune-server
  ports:
  - port: {{ .Values.backend.port }}
    targetPort: {{ .Values.backend.port }}
    protocol: TCP
