apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: app-configmap
data:
  FRONTEND_URL: https://{{ .Values.ratathune.host }}
  HOST: 0.0.0.0
  GOOGLE_CALLBACK_URL: https://api.{{ .Values.ratathune.host }}/google/callback
