apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: ratathune-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ratathune-front
  template:
    metadata:
      labels:
        app: ratathune-front
    spec:
      containers:
      - name: ratathune-front
        image: {{ .Values.image.repository }}-front:{{ .Values.image.tag }}
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: {{ .Values.frontend.port }}
